// <auto-generated />
using DevCapacityApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevCapacityApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250926104439_AddStatusEntity")]
    partial class AddStatusEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DevCapacityApi.Models.Engineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("DevCapacityApi.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("DevCapacityApi.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.HasIndex("ParentTeam");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DevCapacityApi.Models.Engineer", b =>
                {
                    b.HasOne("DevCapacityApi.Models.Team", "Team")
                        .WithMany("Engineers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DevCapacityApi.Models.Team", b =>
                {
                    b.HasOne("DevCapacityApi.Models.Team", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTeam")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DevCapacityApi.Models.Team", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Engineers");
                });
#pragma warning restore 612, 618
        }
    }
}
